version: '3'
services:
    web:
        build: etc/nginx
        container_name: nginx
        restart: always
        ports:
        volumes:
            - ./etc/ssl:/etc/ssl
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - "./www:/var/www/html"
        env_file: 
            - ".env"
        ports:
            - ${PORT_HTTP}:80
            - ${PORT_HTTPS}:443
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "./www:/var/www/html"
    mysqldb:
        build: etc/mysql
        container_name: mysqldb
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - ${PORT_MYSQL}:3306
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
